In [2]:
import yfinance as yf
import numpy as np
import pandas as pd

In [4]:
tickerSymbol = 'AMD'

#get data on this ticker
tickerData = yf.Ticker(tickerSymbol)

#get the historical prices for this ticker
tickerDf = tickerData.history(period='1d', start='2020-1-1', end='2020-4-3')

#see your data
tickerDf.to_csv('amd.csv', index=False)

In [6]:
tickerDf#.plot()

             Open   High    Low  Close    Volume  Dividends  Stock Splits
Date
2020-01-02  46.86  49.25  46.63  49.10  80331100          0             0
2020-01-03  48.03  49.39  47.54  48.60  73127400          0             0
2020-01-06  48.02  48.86  47.86  48.39  47934900          0             0
2020-01-07  49.35  49.39  48.04  48.25  58061400          0             0
2020-01-08  47.85  48.30  47.14  47.83  53767000          0             0
...           ...    ...    ...    ...       ...        ...           ...
2020-03-27  46.32  47.98  45.90  46.58  74599200          0             0
2020-03-30  47.24  48.46  46.66  47.86  68486600          0             0
2020-03-31  47.93  48.53  45.16  45.48  83483700          0             0
2020-04-01  44.18  46.85  43.16  43.66  92083100          0             0
2020-04-02  43.40  45.28  43.10  44.49  79024100          0             0

[64 rows x 7 columns]